//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.CarTrade.Services.Client.CarManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarManagementService.ICarManagementService")]
    public interface ICarManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/GetCars", ReplyAction="http://tempuri.org/ICarManagementService/GetCarsResponse")]
        Demo.CarTrade.Entity.Car[] GetCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/GetCars", ReplyAction="http://tempuri.org/ICarManagementService/GetCarsResponse")]
        System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car[]> GetCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/CreateCar", ReplyAction="http://tempuri.org/ICarManagementService/CreateCarResponse")]
        Demo.CarTrade.Entity.Car CreateCar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/CreateCar", ReplyAction="http://tempuri.org/ICarManagementService/CreateCarResponse")]
        System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car> CreateCarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/UpdateCar", ReplyAction="http://tempuri.org/ICarManagementService/UpdateCarResponse")]
        Demo.CarTrade.Entity.Car UpdateCar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/UpdateCar", ReplyAction="http://tempuri.org/ICarManagementService/UpdateCarResponse")]
        System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car> UpdateCarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/DeleteCar", ReplyAction="http://tempuri.org/ICarManagementService/DeleteCarResponse")]
        Demo.CarTrade.Entity.Car DeleteCar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManagementService/DeleteCar", ReplyAction="http://tempuri.org/ICarManagementService/DeleteCarResponse")]
        System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car> DeleteCarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarManagementServiceChannel : Demo.CarTrade.Services.Client.CarManagementService.ICarManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarManagementServiceClient : System.ServiceModel.ClientBase<Demo.CarTrade.Services.Client.CarManagementService.ICarManagementService>, Demo.CarTrade.Services.Client.CarManagementService.ICarManagementService {
        
        public CarManagementServiceClient() {
        }
        
        public CarManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Demo.CarTrade.Entity.Car[] GetCars() {
            return base.Channel.GetCars();
        }
        
        public System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car[]> GetCarsAsync() {
            return base.Channel.GetCarsAsync();
        }
        
        public Demo.CarTrade.Entity.Car CreateCar() {
            return base.Channel.CreateCar();
        }
        
        public System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car> CreateCarAsync() {
            return base.Channel.CreateCarAsync();
        }
        
        public Demo.CarTrade.Entity.Car UpdateCar() {
            return base.Channel.UpdateCar();
        }
        
        public System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car> UpdateCarAsync() {
            return base.Channel.UpdateCarAsync();
        }
        
        public Demo.CarTrade.Entity.Car DeleteCar() {
            return base.Channel.DeleteCar();
        }
        
        public System.Threading.Tasks.Task<Demo.CarTrade.Entity.Car> DeleteCarAsync() {
            return base.Channel.DeleteCarAsync();
        }
    }
}
